
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '70262318007A5AA7BC48F1C80E02046A'
    
_lr_action_items = {'MOVE':([0,],[6,]),'QUIT':([0,],[7,]),'$end':([3,5,7,8,10,14,],[0,-3,-8,-1,-2,-7,]),'NOUN':([1,9,11,12,13,],[10,14,-6,-5,-4,]),'TALK':([0,],[4,]),'JOIN':([2,4,6,],[11,12,13,]),'LOOK':([0,],[2,]),'DEFINITEART':([1,11,12,13,],[9,-6,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'def_noun':([1,],[8,]),'action':([0,],[1,]),'statement':([0,],[3,]),'quit':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> action def_noun','statement',2,'p_statement','game.py',90),
  ('statement -> action NOUN','statement',2,'p_statement','game.py',91),
  ('statement -> quit','statement',1,'p_statement','game.py',92),
  ('action -> MOVE JOIN','action',2,'p_statement_action','game.py',101),
  ('action -> TALK JOIN','action',2,'p_statement_action','game.py',102),
  ('action -> LOOK JOIN','action',2,'p_statement_action','game.py',103),
  ('def_noun -> DEFINITEART NOUN','def_noun',2,'p_statement_def_noun','game.py',109),
  ('quit -> QUIT','quit',1,'p_quit','game.py',113),
]
