COMP603PROJECT

Authors: Joseph Walker, Mentu, Deep, Ori, Sarthak

== What are you working on? 

Text adventure game being able to take a lot of different commands in.

Example:
http://adamcadre.ac/if/varicella.html[varicella]



== What's your implementation language.

Created in Python 3.0:

https://www.python.org/[python 3.0]

using Ply for tokenizing and parsing:

http://www.dabeaz.com/ply/[Ply]

== What have you done so far?  Did you meet your expectations for this week yet?

Week of 7/13/2015:

Complete: 

Nothing

Expectations:

Starting Area with a basic level tokenizer/parser.

Week of 7/20/2015:

Complete: 

Basic Tokenizer

Expectations:

Starting Area with a basic level tokenizer/parser must be completed.

Proper delegation of work, and the separate sections of the map being created from a base object.

A full story for the game.

== What do you hope to accomplish by next week? How? (Who’s doing what, if this is a team?)

Proper project plan for whole team

== What do you need to move forward

Nothing as of this moment.