
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '11A2C58796EAEF2037193A9B91F1D14C'
    
_lr_action_items = {'NOUN':([2,],[3,]),'DEFINITEART':([0,],[2,]),'$end':([1,3,],[0,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'def_noun':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> def_noun","S'",1,None,None,None),
  ('statement -> action def_noun','statement',2,'p_statement','game.py',70),
  ('statement -> action NOUN','statement',2,'p_statement','game.py',71),
  ('action -> MOVE JOIN','action',2,'p_statement_action','game.py',75),
  ('action -> TALK JOIN','action',2,'p_statement_action','game.py',76),
  ('action -> LOOK JOIN','action',2,'p_statement_action','game.py',77),
  ('def_noun -> DEFINITEART NOUN','def_noun',2,'p_statement_def_noun','game.py',82),
]
